# Generated by Django 4.2.4 on 2023-10-13 05:47

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=100, verbose_name='имя сертификата')),
                ('certificate_created', models.CharField(max_length=50, verbose_name='сертификат создан')),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='media/photo/portfolio', verbose_name='изображение портфолио')),
                ('certificate_slug', autoslug.fields.AutoSlugField(editable=True, populate_from='certificate_name', unique=True, verbose_name='слизняк сертификат')),
            ],
            options={
                'verbose_name': 'сертификат',
                'verbose_name_plural': 'сертификат',
            },
        ),
    ]
