# Generated by Django 4.2.4 on 2023-10-13 05:47

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_slug', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='portfolio_slug', unique=True)),
            ],
            options={
                'verbose_name': 'слизняк портфолио',
                'verbose_name_plural': 'слизняк портфолио',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader_name', models.CharField(max_length=50, verbose_name='имя загрузившего')),
                ('portfolio_title', models.CharField(max_length=100, verbose_name='название портфолио')),
                ('portfolio_text', models.TextField(blank=True, max_length=300, null=True, verbose_name='текст портфолио')),
                ('portfolio_link', models.CharField(max_length=300, verbose_name='ссылка на портфолио')),
                ('portfolio_image', models.ImageField(blank=True, null=True, upload_to='media/photo/portfolio', verbose_name='изображение портфолио')),
                ('portfolio_video', models.FileField(blank=True, null=True, upload_to='media/video/portfolio', verbose_name='портфолио видео')),
                ('portfolio_data', models.DateTimeField(auto_now_add=True)),
                ('portfolio_slug', autoslug.fields.AutoSlugField(editable=True, populate_from='portfolio_title', unique=True, verbose_name='слизняк портфолио')),
                ('portfolio_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfoliocategory', verbose_name='категория портфолио')),
            ],
            options={
                'verbose_name': 'портфолио',
                'verbose_name_plural': 'портфолио',
            },
        ),
    ]
