# Generated by Django 4.2.4 on 2023-10-13 05:47

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography_title', models.CharField(max_length=80, verbose_name='название биографии')),
                ('biography_text', models.CharField(max_length=80, verbose_name='текст биографии')),
                ('biography_slug', autoslug.fields.AutoSlugField(editable=True, populate_from='biography_title', unique=True, verbose_name='слизняк биография')),
            ],
            options={
                'verbose_name': 'Биографии',
                'verbose_name_plural': 'Биографии',
            },
        ),
    ]
