# Generated by Django 4.2.4 on 2023-10-13 05:47

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_title', models.CharField(max_length=70, verbose_name='название навыка')),
                ('skills_text', models.CharField(max_length=150, verbose_name='текст навыков')),
                ('skills_slug', autoslug.fields.AutoSlugField(editable=True, populate_from='skills_title', unique=True, verbose_name='слизняк навыка')),
            ],
            options={
                'verbose_name': 'навыки',
                'verbose_name_plural': 'навыки',
            },
        ),
    ]
