# Generated by Django 4.2.4 on 2023-10-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150, verbose_name='имя пользователя')),
                ('user_email', models.EmailField(max_length=200, verbose_name='адрес электронной почты')),
                ('user_message', models.TextField(max_length=900, verbose_name='сообщение пользователя')),
            ],
            options={
                'verbose_name': 'почтовая форма',
                'verbose_name_plural': 'почтовая форма',
            },
        ),
    ]
